### ISSUE TITLE
More settings to add

### ISSUE THREAD

**Issue by j127** [dfkt/firefox-tweaks#11]
Here are some more useful settings:

    // Don't connect to remote links on hover
    // See http://news.slashdot.org/story/15/08/14/2321202/how-to-quash-firefoxs-silent-requests
    user_pref("network.http.speculative-parallel-limit", 0);
    // Don't autofill URL bar, because it's unpredictable and slower
    user_pref("browser.urlbar.autoFill", false);
    // Open new tabs in background for faster browsing
    user_pref("browser.search.context.loadInBackground", true);
    // Don't select entire URL, since ctrl-l does that
    user_pref("browser.urlbar.clickSelectsAll", false);

**Comment by dfkt** [comment]
Thank you, I added the remote link setting, this seems useful.

The autofill and select settings I see no difference to default behavior, am I missing something? (Autofill doesn't seem slow for me, even on a wimpy Atom netbook, with both settings - and IMO triple-click for 'select all' is awesome, I wish all applications would do that.)

The 'open new tabs in background' setting is actually 'browser.tabs.loadInBackground', which is enabled by default - the browser.search.context.loadInBackground' setting does this: https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/browser.search.context.loadInBackground - which is useful as well, I added it too.

**Comment by j127** [comment]
The autoselect thing is only a problem on Windows, I think. If you're using Linux, it works the correct way by default. I'm not sure about Mac.

I mean that autofill is slower from an operator's standpoint. If a behavior changes with each attempt at an action, it takes extra cognitive load to process what is going on. If the browser knows about a URL, it will autofill, but if it doesn't, it won't. You have to wait a short moment to process whether autofill happened or not.

If you know that you already visited example.com, you can press `ctrl-l` (that's an L -- much faster than triple-clicking) and get to the address bar. Then type `ex` and `TAB`. You don't need to think about it. If you allow auto-filling, then you do need to think about whether you're going to need the `TAB` key or `Enter/return` key next.

It may seem like a minor point, but it does make a difference in speed---kind of like using arrow keys in Vim. A one second delay can be painfully slow when there is a faster way.

I think that auto-fill makes sense on mobile, but not on desktop.

`browser.search.context.loadInBackground` allows you to speedily search the Web by double-clicking on a word, right clicking, and then pressing `s`. (If it's a URL, then press `t` instead of `s`.) That will open the search in a new background tab. If it opens in a foreground tab, and you wanted to do three searches and finish reading the article before looking at the other tab, it interferes with the reading of the first article. You can still get to the next tabs with a quick `ctrl-TAB`.

Just my personal preference, and I know that I take keyboard efficiency way too seriously. :)

(I already put all my preferred settings in a user.js file, so these are just suggestions.)

**Comment by j127** [comment]
I just remembered that I have an explanation of some of the settings [over here](http://blog.joshnotes.com/customize-firefox-about-config/).

**Comment by floalma** [comment]
Dear Dfkt,
Just a few questions, you wrote the following "Type 'google' in about:config and delete most of the links (the ones that won't break anything, that's up to you).
Also search through these to delete links from:
browser.contentHandlers
browser.safebrowsing
browser.search
gecko.handlerService"

After typing google, I have the following:
browser.safebrowsing.appRepURL https://sb-ssl.google.com/safebrowsing/clientreport/download?key=%GOOGLE_API_KEY%

browser.safebrowsing.gethashURL https://safebrowsing.google.com/safebrowsing/gethash?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2

browser.safebrowsing.malware.reportURL  https://safebrowsing.google.com/safebrowsing/diagnostic?client=%NAME%&hl=%LOCALE%&site=

browser.safebrowsing.updateURL  https://safebrowsing.google.com/safebrowsing/downloads?client=SAFEBROWSING_ID&appver=%VERSION%&pver=2.2&key=%GOOGLE_API_KEY%

Do I have to remove the corresponding values for these strings ??

I don't have 'browser.contentHandlers' when typing google, but If I make a search on config, I got a few strings, do I have to remove it ? Please, let me know more details, thanks !

**Comment by dfkt** [comment]
Hi floalma, I updated the settings with precise preference descriptions (both for the new FF43 "safe browsing" and the old ones). Please look at the current version of the file - I hope that helps.

In theory, just disabling safe browsing with `browser.safebrowsing.enabled` and `browser.safebrowsing.malware.enabled` set to false should be enough. Removing the URLs is just an additional paranoid way of making sure.

**Comment by floalma** [comment]
Thank you dfkt !! I already disabled safe browsing but I wanted to test as paranoid mode. ;)
