### ISSUE TITLE
Any way to automate all settings through script?

### ISSUE THREAD

**Issue by apexkid** [dfkt/firefox-tweaks#2]

**Comment by j127** [comment]
I created a `user.js` file from the txt file. You can get it over here:
https://github.com/j127/firefox-tweaks

If you put the settings in a `user.js` file and drop it in your Firefox Profile folder, it will change the settings for you. See the README file on my fork.

If you want to merge it back in, I could do a pull request. I added a few more good settings there too, based on [this blog post](http://blog.joshnotes.com/customize-firefox-about-config/).

**Comment by dfkt** [comment]
Credits would be nice :p

**Comment by j127** [comment]
It says "forked from dfkt/firefox-tweaks" with 2 contributors, so I thought it was obvious. :)

I just put a large note at the top of the README now though, to make it clear at a casual glance.
