### ISSUE TITLE
Spelling mistake in "firefox-tweaks.txt"

### ISSUE THREAD

**Issue by tmthywynn8** [dfkt/firefox-tweaks#7]
*Problem*: In the "Disable 'safe browsing'"section, there's a spelling mistake in one of the Boolean settings:
browser.safebrowsing.maleware.enabled - false
It should be:
browser.safebrowsing.malware.enabled - false

*Solution*: Delete the 'e' in 'maleware'.

**Comment by dfkt** [comment]
Thank you. Fixed.
