### ISSUE TITLE
network.http.speculative-parallel-limit

### ISSUE THREAD

**Issue by ganego** [dfkt/firefox-tweaks#9]
See http://www.ghacks.net/2015/08/16/block-firefox-from-connecting-to-sites-when-you-hover-over-links/

> If you hover over links in the Firefox browser for instance, connections are made to those resources automatically by the browser to improve the loading speed. To be precise, TCP and SSL handshakes are set up in advance but page contents are not downloaded until a click on the link is registered.

> * Use the search to find network.http.speculative-parallel-limit.
> * Double-click on the preference and change its value from 6 to 0.

**Comment by dfkt** [comment]
Thanks, I added that setting.
